# Generated by Django 5.0.7 on 2024-07-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blum',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blum',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.socialmedia'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
